// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB.Models;

#nullable disable

namespace WEB.Migrations
{
    [DbContext(typeof(BerberContext))]
    partial class BerberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HizmetId");

                    b.HasIndex("SalonId");

                    b.ToTable("Calisanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceYears = 5,
                            HizmetId = 1,
                            Name = "Ahmet Yılmaz",
                            SalonId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExperienceYears = 3,
                            HizmetId = 2,
                            Name = "Mehmet Çelik",
                            SalonId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExperienceYears = 10,
                            HizmetId = 3,
                            Name = "Ayşe Demir",
                            SalonId = 2
                        },
                        new
                        {
                            Id = 4,
                            ExperienceYears = 8,
                            HizmetId = 4,
                            Name = "Fatma Kaya",
                            SalonId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExperienceYears = 15,
                            HizmetId = 1,
                            Name = "Hasan Ak",
                            SalonId = 3
                        },
                        new
                        {
                            Id = 6,
                            ExperienceYears = 6,
                            HizmetId = 5,
                            Name = "Zehra Şen",
                            SalonId = 3
                        },
                        new
                        {
                            Id = 7,
                            ExperienceYears = 20,
                            HizmetId = 2,
                            Name = "Ali Güneş",
                            SalonId = 4
                        },
                        new
                        {
                            Id = 8,
                            ExperienceYears = 12,
                            HizmetId = 3,
                            Name = "Emre Öztürk",
                            SalonId = 4
                        },
                        new
                        {
                            Id = 9,
                            ExperienceYears = 7,
                            HizmetId = 4,
                            Name = "Elif Taş",
                            SalonId = 5
                        },
                        new
                        {
                            Id = 10,
                            ExperienceYears = 2,
                            HizmetId = 1,
                            Name = "İrem Bulut",
                            SalonId = 5
                        });
                });

            modelBuilder.Entity("WEB.Models.CalisanHizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("HizmetId");

                    b.ToTable("CalisanHizmetleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalisanId = 1,
                            HizmetId = 1
                        },
                        new
                        {
                            Id = 2,
                            CalisanId = 1,
                            HizmetId = 2
                        },
                        new
                        {
                            Id = 3,
                            CalisanId = 2,
                            HizmetId = 1
                        },
                        new
                        {
                            Id = 4,
                            CalisanId = 2,
                            HizmetId = 3
                        },
                        new
                        {
                            Id = 5,
                            CalisanId = 3,
                            HizmetId = 2
                        },
                        new
                        {
                            Id = 6,
                            CalisanId = 3,
                            HizmetId = 4
                        },
                        new
                        {
                            Id = 7,
                            CalisanId = 4,
                            HizmetId = 1
                        },
                        new
                        {
                            Id = 8,
                            CalisanId = 4,
                            HizmetId = 5
                        },
                        new
                        {
                            Id = 9,
                            CalisanId = 5,
                            HizmetId = 3
                        },
                        new
                        {
                            Id = 10,
                            CalisanId = 5,
                            HizmetId = 4
                        });
                });

            modelBuilder.Entity("WEB.Models.CalismaSaati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.ToTable("CalismaSaatleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalisanId = 1,
                            DayOfWeek = "Pazartesi",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CalisanId = 1,
                            DayOfWeek = "Salı",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CalisanId = 1,
                            DayOfWeek = "Çarşamba",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CalisanId = 1,
                            DayOfWeek = "Perşembe",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CalisanId = 1,
                            DayOfWeek = "Cuma",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CalisanId = 1,
                            DayOfWeek = "Cumartesi",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CalisanId = 2,
                            DayOfWeek = "Pazartesi",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CalisanId = 2,
                            DayOfWeek = "Salı",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CalisanId = 2,
                            DayOfWeek = "Çarşamba",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CalisanId = 2,
                            DayOfWeek = "Perşembe",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            CalisanId = 2,
                            DayOfWeek = "Cuma",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            CalisanId = 2,
                            DayOfWeek = "Cumartesi",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 30, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            CalisanId = 3,
                            DayOfWeek = "Pazartesi",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            CalisanId = 3,
                            DayOfWeek = "Salı",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            CalisanId = 3,
                            DayOfWeek = "Çarşamba",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            CalisanId = 3,
                            DayOfWeek = "Perşembe",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            CalisanId = 3,
                            DayOfWeek = "Cuma",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            CalisanId = 3,
                            DayOfWeek = "Cumartesi",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("WEB.Models.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hizmetler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 30,
                            Name = "Saç Kesimi",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 45,
                            Name = "Manikür",
                            Price = 80m
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 60,
                            Name = "Pedikür",
                            Price = 100m
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 90,
                            Name = "Saç Boyama",
                            Price = 200m
                        },
                        new
                        {
                            Id = 5,
                            DurationMinutes = 120,
                            Name = "Cilt Bakımı",
                            Price = 150m
                        },
                        new
                        {
                            Id = 6,
                            DurationMinutes = 25,
                            Name = "Sakal Kesimi",
                            Price = 40m
                        },
                        new
                        {
                            Id = 7,
                            DurationMinutes = 60,
                            Name = "Masaj",
                            Price = 250m
                        },
                        new
                        {
                            Id = 8,
                            DurationMinutes = 15,
                            Name = "Saç Yıkama",
                            Price = 20m
                        },
                        new
                        {
                            Id = 9,
                            DurationMinutes = 30,
                            Name = "Yüz Temizleme",
                            Price = 100m
                        },
                        new
                        {
                            Id = 10,
                            DurationMinutes = 20,
                            Name = "Bıyık Şekillendirme",
                            Price = 30m
                        });
                });

            modelBuilder.Entity("WEB.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HizmetId");

                    b.HasIndex("SalonId");

                    b.HasIndex("UserId");

                    b.ToTable("Randevular");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentTime = new DateTime(2024, 12, 23, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 1,
                            Price = 50.0m,
                            SalonId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentTime = new DateTime(2024, 12, 23, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 2,
                            Price = 30.0m,
                            SalonId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentTime = new DateTime(2024, 12, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 3,
                            Price = 100.0m,
                            SalonId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentTime = new DateTime(2024, 12, 23, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 4,
                            Price = 150.0m,
                            SalonId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentTime = new DateTime(2024, 12, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 5,
                            Price = 75.0m,
                            SalonId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentTime = new DateTime(2024, 12, 24, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 1,
                            Price = 50.0m,
                            SalonId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            AppointmentTime = new DateTime(2024, 12, 24, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 2,
                            Price = 30.0m,
                            SalonId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            AppointmentTime = new DateTime(2024, 12, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 3,
                            Price = 100.0m,
                            SalonId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            AppointmentTime = new DateTime(2024, 12, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 4,
                            Price = 150.0m,
                            SalonId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            AppointmentTime = new DateTime(2024, 12, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HizmetId = 5,
                            Price = 75.0m,
                            SalonId = 5,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("WEB.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Salonlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "02124567890",
                            Location = "İstanbul",
                            Name = "Elite Güzellik Salonu"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "03124567890",
                            Location = "Ankara",
                            Name = "Lüks Kuaför"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "02324567890",
                            Location = "İzmir",
                            Name = "Güzellik Merkezi"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "02424567890",
                            Location = "Antalya",
                            Name = "Bakım ve Spa"
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "02224567890",
                            Location = "Bursa",
                            Name = "Zen Saç Stüdyosu"
                        },
                        new
                        {
                            Id = 6,
                            ContactNumber = "03224567890",
                            Location = "Adana",
                            Name = "Royal Saç Merkezi"
                        },
                        new
                        {
                            Id = 7,
                            ContactNumber = "03424567890",
                            Location = "Gaziantep",
                            Name = "Luxury Hair"
                        },
                        new
                        {
                            Id = 8,
                            ContactNumber = "03524567890",
                            Location = "Kayseri",
                            Name = "Dream Spa"
                        },
                        new
                        {
                            Id = 9,
                            ContactNumber = "02224567891",
                            Location = "Eskişehir",
                            Name = "Modern Güzellik"
                        },
                        new
                        {
                            Id = 10,
                            ContactNumber = "03324567890",
                            Location = "Konya",
                            Name = "Prestij Bakım Merkezi"
                        });
                });

            modelBuilder.Entity("WEB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet.yilmaz@gmail.com",
                            Name = "Ahmet Yılmaz",
                            PasswordHash = "AQAAAAIAAYagAAAAEPDXXWDU/gZ4lOCqGqgJnZkT2ez4WMDsTCgiyL9W294ggqvLwliefoQUNzulApXW7Q==",
                            Phone = "05331234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ayse.demir@gmail.com",
                            Name = "Ayşe Demir",
                            PasswordHash = "AQAAAAIAAYagAAAAEME9cKMgU+LXKPxB/6o6f6r31MbJ5HfRGNF0sRKjteBwcg87xLIBfwIYUifyb2WbUw==",
                            Phone = "05339876543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "fatma.celik@gmail.com",
                            Name = "Fatma Çelik",
                            PasswordHash = "AQAAAAIAAYagAAAAEDx7YEFRPupmS6hMO4EIJXrn6WXCH4mqlI6ptscZSyppgPYWbcif7gKc5+26jnphsA==",
                            Phone = "05431234567"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mehmet.kara@gmail.com",
                            Name = "Mehmet Kara",
                            PasswordHash = "AQAAAAIAAYagAAAAEP7x5t3DumUhlxzpN0Nyo9w+FJilqtf8NTFPs61ZIaNwmL+fAPMutvTEW3zafqA2hw==",
                            Phone = "05439876543"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ali.can@gmail.com",
                            Name = "Ali Can",
                            PasswordHash = "AQAAAAIAAYagAAAAEDY9yJjbcv37LegabMDRSu00YXfmDScDnMkt61ivciqN6CjX8V3Zcj9MeontfDCiBA==",
                            Phone = "05551234567"
                        },
                        new
                        {
                            Id = 6,
                            Email = "merve.sen@gmail.com",
                            Name = "Merve Şen",
                            PasswordHash = "AQAAAAIAAYagAAAAEOeyIX5owWngPfHseUVCN2BPwDpSlU0xa6oHr+JEza4bEGKstRORDXHYYD+iBiKJOw==",
                            Phone = "05631234567"
                        },
                        new
                        {
                            Id = 7,
                            Email = "burak.arslan@gmail.com",
                            Name = "Burak Arslan",
                            PasswordHash = "AQAAAAIAAYagAAAAEGVF4t5mIe/LRFVUR/gg1QcsWWdVGrXfX9y717zc4bjL0S9Llz4yhbWk+c63etjrNA==",
                            Phone = "05471234567"
                        },
                        new
                        {
                            Id = 8,
                            Email = "emre.yildiz@gmail.com",
                            Name = "Emre Yıldız",
                            PasswordHash = "AQAAAAIAAYagAAAAEPatktJ+9d5Wv4FZtOMWEhZ3DZi5d0Pq0u0B8ioMDRhpRPpnULBg+raOQzBdTW3/Sw==",
                            Phone = "05381234567"
                        },
                        new
                        {
                            Id = 9,
                            Email = "elif.gul@gmail.com",
                            Name = "Elif Gül",
                            PasswordHash = "AQAAAAIAAYagAAAAECQSQI9CE/L+KuZiALJb2I6NXfD2CzDrsao6oWxDoB7Q5hwVQwM10QBBz+Vzg91PEg==",
                            Phone = "05569876543"
                        },
                        new
                        {
                            Id = 10,
                            Email = "huseyin.demir@gmail.com",
                            Name = "Hüseyin Demir",
                            PasswordHash = "AQAAAAIAAYagAAAAEG2NB1nvJP+CC0shu4ixPQck4sCaIm8LUJJPN8yreopIVqdtY61AG+OevgHoKtj6WA==",
                            Phone = "05351239876"
                        });
                });

            modelBuilder.Entity("WEB.Models.Calisan", b =>
                {
                    b.HasOne("WEB.Models.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Salon", "Salon")
                        .WithMany("Calisanlar")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hizmet");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("WEB.Models.CalisanHizmet", b =>
                {
                    b.HasOne("WEB.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("WEB.Models.CalismaSaati", b =>
                {
                    b.HasOne("WEB.Models.Calisan", "Calisan")
                        .WithMany("CalismaSaatleri")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("WEB.Models.Randevu", b =>
                {
                    b.HasOne("WEB.Models.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Salon", "Salon")
                        .WithMany("Randevular")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.User", "User")
                        .WithMany("Randevular")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hizmet");

                    b.Navigation("Salon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WEB.Models.Calisan", b =>
                {
                    b.Navigation("CalismaSaatleri");
                });

            modelBuilder.Entity("WEB.Models.Salon", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("WEB.Models.User", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
