// <auto-generated />
using System;
using Bshop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241222000701_m3")]
    partial class m3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bshop.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Calisans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceYears = 5,
                            FullName = "Mehmet Yılmaz",
                            SalonId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExperienceYears = 3,
                            FullName = "Ayşe Demir",
                            SalonId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExperienceYears = 4,
                            FullName = "Fatma Kaya",
                            SalonId = 3
                        },
                        new
                        {
                            Id = 4,
                            ExperienceYears = 6,
                            FullName = "Ali Can",
                            SalonId = 4
                        },
                        new
                        {
                            Id = 5,
                            ExperienceYears = 2,
                            FullName = "Elif Öz",
                            SalonId = 5
                        },
                        new
                        {
                            Id = 6,
                            ExperienceYears = 7,
                            FullName = "Burak Şahin",
                            SalonId = 6
                        },
                        new
                        {
                            Id = 7,
                            ExperienceYears = 4,
                            FullName = "Deniz Arslan",
                            SalonId = 7
                        },
                        new
                        {
                            Id = 8,
                            ExperienceYears = 5,
                            FullName = "Zeynep Aydın",
                            SalonId = 8
                        },
                        new
                        {
                            Id = 9,
                            ExperienceYears = 3,
                            FullName = "Okan Güneş",
                            SalonId = 9
                        },
                        new
                        {
                            Id = 10,
                            ExperienceYears = 4,
                            FullName = "Selin Toprak",
                            SalonId = 10
                        });
                });

            modelBuilder.Entity("Bshop.Models.CalisanHizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HizmetId");

                    b.HasIndex("CalisanId", "HizmetId")
                        .IsUnique();

                    b.ToTable("CalisanHizmets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalisanId = 1,
                            HizmetId = 1
                        },
                        new
                        {
                            Id = 2,
                            CalisanId = 1,
                            HizmetId = 2
                        },
                        new
                        {
                            Id = 3,
                            CalisanId = 2,
                            HizmetId = 2
                        },
                        new
                        {
                            Id = 4,
                            CalisanId = 2,
                            HizmetId = 3
                        },
                        new
                        {
                            Id = 5,
                            CalisanId = 3,
                            HizmetId = 1
                        },
                        new
                        {
                            Id = 6,
                            CalisanId = 3,
                            HizmetId = 3
                        },
                        new
                        {
                            Id = 7,
                            CalisanId = 4,
                            HizmetId = 4
                        },
                        new
                        {
                            Id = 8,
                            CalisanId = 5,
                            HizmetId = 7
                        },
                        new
                        {
                            Id = 9,
                            CalisanId = 6,
                            HizmetId = 5
                        },
                        new
                        {
                            Id = 10,
                            CalisanId = 7,
                            HizmetId = 6
                        },
                        new
                        {
                            Id = 11,
                            CalisanId = 8,
                            HizmetId = 2
                        },
                        new
                        {
                            Id = 12,
                            CalisanId = 9,
                            HizmetId = 4
                        },
                        new
                        {
                            Id = 13,
                            CalisanId = 10,
                            HizmetId = 8
                        });
                });

            modelBuilder.Entity("Bshop.Models.CalismaSaati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("Gun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.ToTable("CalismaSaatis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 1,
                            Gun = 1
                        },
                        new
                        {
                            Id = 2,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 1,
                            Gun = 2
                        },
                        new
                        {
                            Id = 3,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 1,
                            Gun = 3
                        },
                        new
                        {
                            Id = 4,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 1,
                            Gun = 4
                        },
                        new
                        {
                            Id = 5,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 2,
                            Gun = 1
                        },
                        new
                        {
                            Id = 6,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 2,
                            Gun = 3
                        },
                        new
                        {
                            Id = 7,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 2,
                            Gun = 5
                        },
                        new
                        {
                            Id = 8,
                            BaslangicSaati = new TimeSpan(0, 8, 30, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 30, 0, 0),
                            CalisanId = 3,
                            Gun = 2
                        },
                        new
                        {
                            Id = 9,
                            BaslangicSaati = new TimeSpan(0, 8, 30, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 30, 0, 0),
                            CalisanId = 3,
                            Gun = 4
                        },
                        new
                        {
                            Id = 10,
                            BaslangicSaati = new TimeSpan(0, 8, 30, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 30, 0, 0),
                            CalisanId = 3,
                            Gun = 6
                        },
                        new
                        {
                            Id = 11,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 4,
                            Gun = 1
                        },
                        new
                        {
                            Id = 12,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 4,
                            Gun = 3
                        },
                        new
                        {
                            Id = 13,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 4,
                            Gun = 5
                        },
                        new
                        {
                            Id = 14,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 5,
                            Gun = 2
                        },
                        new
                        {
                            Id = 15,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 5,
                            Gun = 4
                        },
                        new
                        {
                            Id = 16,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            CalisanId = 6,
                            Gun = 1
                        },
                        new
                        {
                            Id = 17,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            CalisanId = 6,
                            Gun = 3
                        },
                        new
                        {
                            Id = 18,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            CalisanId = 6,
                            Gun = 5
                        },
                        new
                        {
                            Id = 19,
                            BaslangicSaati = new TimeSpan(0, 9, 30, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 30, 0, 0),
                            CalisanId = 7,
                            Gun = 2
                        },
                        new
                        {
                            Id = 20,
                            BaslangicSaati = new TimeSpan(0, 9, 30, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 30, 0, 0),
                            CalisanId = 7,
                            Gun = 4
                        },
                        new
                        {
                            Id = 21,
                            BaslangicSaati = new TimeSpan(0, 9, 30, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 30, 0, 0),
                            CalisanId = 7,
                            Gun = 6
                        },
                        new
                        {
                            Id = 22,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 8,
                            Gun = 1
                        },
                        new
                        {
                            Id = 23,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 8,
                            Gun = 3
                        },
                        new
                        {
                            Id = 24,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            CalisanId = 8,
                            Gun = 5
                        },
                        new
                        {
                            Id = 25,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 9,
                            Gun = 2
                        },
                        new
                        {
                            Id = 26,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 9,
                            Gun = 4
                        },
                        new
                        {
                            Id = 27,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            CalisanId = 9,
                            Gun = 6
                        },
                        new
                        {
                            Id = 28,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            CalisanId = 10,
                            Gun = 2
                        },
                        new
                        {
                            Id = 29,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            CalisanId = 10,
                            Gun = 4
                        },
                        new
                        {
                            Id = 30,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            CalisanId = 10,
                            Gun = 6
                        });
                });

            modelBuilder.Entity("Bshop.Models.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hizmets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Profesyonel saç kesimi hizmeti.",
                            DurationMinutes = 30,
                            Name = "Saç Kesimi",
                            PhotoUrl = "https://example.com/photos/sac_kesimi.jpg",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Derinlemesine cilt bakımı.",
                            DurationMinutes = 60,
                            Name = "Cilt Bakımı",
                            PhotoUrl = "https://example.com/photos/cilt_bakimi.jpg",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bakımlı tırnaklar için manikür.",
                            DurationMinutes = 45,
                            Name = "Manikür",
                            PhotoUrl = "https://example.com/photos/manikur.jpg",
                            Price = 150m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Profesyonel saç boyama hizmeti.",
                            DurationMinutes = 90,
                            Name = "Saç Boyama",
                            PhotoUrl = "https://example.com/photos/sac_boyama.jpg",
                            Price = 250m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pürüzsüz cilt için epilasyon hizmeti.",
                            DurationMinutes = 75,
                            Name = "Epilasyon",
                            PhotoUrl = "https://example.com/photos/epilasyon.jpg",
                            Price = 180m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Rahatlatıcı masaj hizmeti.",
                            DurationMinutes = 60,
                            Name = "Masaj",
                            PhotoUrl = "https://example.com/photos/masaj.jpg",
                            Price = 220m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Özel tırnak tasarımları.",
                            DurationMinutes = 50,
                            Name = "Tırnak Tasarımı",
                            PhotoUrl = "https://example.com/photos/tirnak_tasarimi.jpg",
                            Price = 170m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Özel günler için profesyonel makyaj.",
                            DurationMinutes = 120,
                            Name = "Profesyonel Makyaj",
                            PhotoUrl = "https://example.com/photos/makyaj.jpg",
                            Price = 300m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Doğal ve uzun kaş ve kirpikler.",
                            DurationMinutes = 40,
                            Name = "Kaş ve Kirpik Uzatma",
                            PhotoUrl = "https://example.com/photos/kas_kirpik_uzatma.jpg",
                            Price = 130m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Cilt yenileyici vücut bakımı hizmeti.",
                            DurationMinutes = 80,
                            Name = "Vücut Bakımı",
                            PhotoUrl = "https://example.com/photos/vucut_bakimi.jpg",
                            Price = 210m
                        });
                });

            modelBuilder.Entity("Bshop.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanHizmetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RandevuSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalisanHizmetId");

                    b.HasIndex("SalonId");

                    b.HasIndex("UserId");

                    b.ToTable("Randevular");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalisanHizmetId = 1,
                            RandevuSaati = new DateTime(2024, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CalisanHizmetId = 3,
                            RandevuSaati = new DateTime(2024, 1, 11, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CalisanHizmetId = 5,
                            RandevuSaati = new DateTime(2024, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CalisanHizmetId = 7,
                            RandevuSaati = new DateTime(2024, 1, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CalisanHizmetId = 9,
                            RandevuSaati = new DateTime(2024, 1, 14, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CalisanHizmetId = 10,
                            RandevuSaati = new DateTime(2024, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CalisanHizmetId = 6,
                            RandevuSaati = new DateTime(2024, 1, 16, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CalisanHizmetId = 2,
                            RandevuSaati = new DateTime(2024, 1, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CalisanHizmetId = 4,
                            RandevuSaati = new DateTime(2024, 1, 18, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CalisanHizmetId = 8,
                            RandevuSaati = new DateTime(2024, 1, 19, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SalonId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Bshop.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Salons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "0212 555 1234",
                            Location = "İstanbul",
                            Name = "Güzellik Merkezi A"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "0312 555 5678",
                            Location = "Ankara",
                            Name = "Saç ve Cilt Studio"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "0232 555 9012",
                            Location = "İzmir",
                            Name = "Elegance Salonu"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "0228 555 3456",
                            Location = "Bursa",
                            Name = "Premium Güzellik"
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "0242 555 7890",
                            Location = "Antalya",
                            Name = "Moda Saç Salonu"
                        },
                        new
                        {
                            Id = 6,
                            ContactNumber = "0322 555 2345",
                            Location = "Adana",
                            Name = "Sihirli Eller"
                        },
                        new
                        {
                            Id = 7,
                            ContactNumber = "0462 555 6789",
                            Location = "Trabzon",
                            Name = "Şıklık Noktası"
                        },
                        new
                        {
                            Id = 8,
                            ContactNumber = "0342 555 0123",
                            Location = "Gaziantep",
                            Name = "Lüks Güzellik"
                        },
                        new
                        {
                            Id = 9,
                            ContactNumber = "0352 555 4567",
                            Location = "Kayseri",
                            Name = "Parlak Saç"
                        },
                        new
                        {
                            Id = 10,
                            ContactNumber = "0332 555 8901",
                            Location = "Konya",
                            Name = "Zarif Cilt Bakımı"
                        });
                });

            modelBuilder.Entity("Bshop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            FullName = "John Doe",
                            Password = "password123",
                            Phone = "0500 000 0000",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            FullName = "Jane Smith",
                            Password = "password123",
                            Phone = "0500 000 0001",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            Password = "password123",
                            Phone = "0500 000 0002",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "michael@example.com",
                            FullName = "Michael Brown",
                            Password = "password123",
                            Phone = "0500 000 0003",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "emily@example.com",
                            FullName = "Emily Davis",
                            Password = "password123",
                            Phone = "0500 000 0004",
                            Role = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "david@example.com",
                            FullName = "David Wilson",
                            Password = "password123",
                            Phone = "0500 000 0005",
                            Role = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "sarah@example.com",
                            FullName = "Sarah Miller",
                            Password = "password123",
                            Phone = "0500 000 0006",
                            Role = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "chris@example.com",
                            FullName = "Chris Martin",
                            Password = "password123",
                            Phone = "0500 000 0007",
                            Role = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "lisa@example.com",
                            FullName = "Lisa Taylor",
                            Password = "password123",
                            Phone = "0500 000 0008",
                            Role = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "tom@example.com",
                            FullName = "Tom Clark",
                            Password = "password123",
                            Phone = "0500 000 0009",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Bshop.Models.Calisan", b =>
                {
                    b.HasOne("Bshop.Models.Salon", "Salon")
                        .WithMany("Calisans")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Bshop.Models.CalisanHizmet", b =>
                {
                    b.HasOne("Bshop.Models.Calisan", "Calisan")
                        .WithMany("CalisanHizmetleri")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bshop.Models.Hizmet", "Hizmet")
                        .WithMany("CalisanHizmetleri")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("Bshop.Models.CalismaSaati", b =>
                {
                    b.HasOne("Bshop.Models.Calisan", "Calisan")
                        .WithMany("CalismaSaatleri")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("Bshop.Models.Randevu", b =>
                {
                    b.HasOne("Bshop.Models.CalisanHizmet", "CalisanHizmet")
                        .WithMany()
                        .HasForeignKey("CalisanHizmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bshop.Models.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bshop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalisanHizmet");

                    b.Navigation("Salon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bshop.Models.Calisan", b =>
                {
                    b.Navigation("CalisanHizmetleri");

                    b.Navigation("CalismaSaatleri");
                });

            modelBuilder.Entity("Bshop.Models.Hizmet", b =>
                {
                    b.Navigation("CalisanHizmetleri");
                });

            modelBuilder.Entity("Bshop.Models.Salon", b =>
                {
                    b.Navigation("Calisans");
                });
#pragma warning restore 612, 618
        }
    }
}
